#!/usr/bin/env -S npx tsx
/**
 * Emits the three SQL files from tmp/reseed/plan.json:
 *   supabase/migrations/<ts>_orgchart_reseed_01_snapshot.sql
 *   supabase/migrations/<ts>_orgchart_reseed_02_apply.sql
 *   scripts/orgchart-reseed-rollback.sql      (NOT in migrations/, manual paste only)
 *   docs/orgchart-reseed-verify.md
 *
 * The migrations are designed to be pasted into Supabase SQL Editor in order.
 * The apply file is wrapped in a transaction; if anything fails it rolls back
 * cleanly. The rollback file is for the case where apply succeeded but you
 * decide later to undo.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

interface KeepAction {
  type: 'keep';
  xp_id: string;
  xp_name_en: string;
  new_name_en: string;
  new_name_fr: string;
  orgchart_id: string;
  new_parent_xp_id: string | null;
  new_parent_orgchart_id: string | null;
  level: 'ministry' | 'department' | 'team';
}
interface InsertAction {
  type: 'insert';
  new_xp_id: string;
  name_en: string;
  name_fr: string;
  orgchart_id: string;
  parent_orgchart_id: string | null;
  parent_xp_id: string | null;
  level: 'ministry' | 'department' | 'team';
}
interface SoftDeleteAction {
  type: 'soft_delete';
  xp_id: string;
  xp_name_en: string;
  reason: string;
  retarget_xp_id: string | null;
  retarget_label: string;
  goals_count: number;
  meetings_count: number;
  events_count: number;
  members_count: number;
}
type Action = KeepAction | InsertAction | SoftDeleteAction;

const tmp = resolve('tmp/reseed');
const plan = JSON.parse(readFileSync(`${tmp}/plan.json`, 'utf8')) as {
  actions: Action[];
};

const ts = process.argv[2] || '20260505155403';
const snapshotFile = `supabase/migrations/${ts}_orgchart_reseed_01_snapshot.sql`;
const applyFile = `supabase/migrations/${ts}_orgchart_reseed_02_apply.sql`;
const rollbackFile = `scripts/orgchart-reseed-rollback.sql`;
const verifyFile = `docs/orgchart-reseed-verify.md`;

const keeps = plan.actions.filter((a) => a.type === 'keep') as KeepAction[];
const inserts = plan.actions.filter((a) => a.type === 'insert') as InsertAction[];
const deletes = plan.actions.filter((a) => a.type === 'soft_delete') as SoftDeleteAction[];

function sql(s: string): string {
  return s.replace(/'/g, "''");
}

// ─────────────────────────────────────────────────────────────────────────
// Snapshot SQL
// ─────────────────────────────────────────────────────────────────────────
const snapshot = `-- Orgchart Reseed: SNAPSHOT (file 01 of 2)
-- Generated by scripts/orgchart-reseed-emit-sql.ts
-- Plan timestamp: ${new Date().toISOString()}
--
-- This migration ONLY copies current state into _reseed_snapshot_* tables.
-- It is non-destructive: no rows in production tables are modified.
-- Apply this BEFORE the reseed apply migration.
-- The rollback script (scripts/orgchart-reseed-rollback.sql) reads from these
-- snapshot tables to restore the prior state if needed.

BEGIN;

-- Manifest table records the snapshot ts and original row counts so rollback
-- can verify there is something to restore.
CREATE TABLE IF NOT EXISTS public._reseed_manifest (
  id text PRIMARY KEY,
  taken_at timestamptz NOT NULL DEFAULT now(),
  ministries_count int NOT NULL,
  people_ministries_count int NOT NULL,
  goals_with_ministry_count int NOT NULL,
  meetings_with_ministry_count int NOT NULL,
  events_with_ministry_count int NOT NULL
);

-- Drop+recreate snapshot tables so this file is idempotent (safe to run twice).
DROP TABLE IF EXISTS public._reseed_snapshot_ministries;
DROP TABLE IF EXISTS public._reseed_snapshot_people_ministries;
DROP TABLE IF EXISTS public._reseed_snapshot_goals_owner;
DROP TABLE IF EXISTS public._reseed_snapshot_meetings_ministry;
DROP TABLE IF EXISTS public._reseed_snapshot_events_ministry;

CREATE TABLE public._reseed_snapshot_ministries AS
  SELECT * FROM public.ministries;

CREATE TABLE public._reseed_snapshot_people_ministries AS
  SELECT * FROM public.people_ministries;

-- Only the FK + identifier columns are needed for the rollback FK repoint.
CREATE TABLE public._reseed_snapshot_goals_owner AS
  SELECT id, owner_ministry_id FROM public.goals WHERE owner_ministry_id IS NOT NULL;

CREATE TABLE public._reseed_snapshot_meetings_ministry AS
  SELECT id, ministry_id FROM public.meetings WHERE ministry_id IS NOT NULL;

CREATE TABLE public._reseed_snapshot_events_ministry AS
  SELECT id, ministry_id FROM public.events WHERE ministry_id IS NOT NULL;

INSERT INTO public._reseed_manifest (
  id, ministries_count, people_ministries_count,
  goals_with_ministry_count, meetings_with_ministry_count, events_with_ministry_count
)
VALUES (
  '${ts}',
  (SELECT count(*) FROM public._reseed_snapshot_ministries),
  (SELECT count(*) FROM public._reseed_snapshot_people_ministries),
  (SELECT count(*) FROM public._reseed_snapshot_goals_owner),
  (SELECT count(*) FROM public._reseed_snapshot_meetings_ministry),
  (SELECT count(*) FROM public._reseed_snapshot_events_ministry)
)
ON CONFLICT (id) DO UPDATE SET
  taken_at = now(),
  ministries_count = EXCLUDED.ministries_count,
  people_ministries_count = EXCLUDED.people_ministries_count,
  goals_with_ministry_count = EXCLUDED.goals_with_ministry_count,
  meetings_with_ministry_count = EXCLUDED.meetings_with_ministry_count,
  events_with_ministry_count = EXCLUDED.events_with_ministry_count;

COMMIT;

-- After running, verify with:
--   SELECT * FROM public._reseed_manifest;
--   SELECT count(*) FROM public._reseed_snapshot_ministries;        -- should equal ministries before reseed
--   SELECT count(*) FROM public._reseed_snapshot_people_ministries;
`;

writeFileSync(snapshotFile, snapshot);
console.log('wrote', snapshotFile);

// ─────────────────────────────────────────────────────────────────────────
// Apply SQL
// ─────────────────────────────────────────────────────────────────────────
const applyParts: string[] = [];
applyParts.push(`-- Orgchart Reseed: APPLY (file 02 of 2)
-- Generated by scripts/orgchart-reseed-emit-sql.ts
-- Plan timestamp: ${new Date().toISOString()}
--
-- DO NOT RUN before the snapshot migration (file 01). This file mutates
-- ministries, people_ministries, goals.owner_ministry_id, meetings.ministry_id,
-- and events.ministry_id. Wrapped in a transaction so partial failure is
-- impossible.

BEGIN;

-- Safety check: snapshot must exist.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public._reseed_manifest WHERE id = '${ts}') THEN
    RAISE EXCEPTION 'Reseed snapshot ${ts} not found. Run the snapshot migration first.';
  END IF;
END $$;
`);

// Step 1: Insert new ministries (orgchart nodes missing locally) — children may
// reference parents inserted in the same step, so order by depth is required.
// Insert top-level (parent_xp_id = null) first, then recurse by parent_xp_id.
applyParts.push(`
-- ── Step 1: Insert new ministry rows for orgchart nodes missing locally ──`);

// Order inserts: top-level first, then by depth.
const insertMap = new Map(inserts.map((i) => [i.new_xp_id, i] as const));
const orderedInserts: InsertAction[] = [];
const visited = new Set<string>();
function addInOrder(i: InsertAction) {
  if (visited.has(i.new_xp_id)) return;
  if (i.parent_xp_id && insertMap.has(i.parent_xp_id) && !visited.has(i.parent_xp_id)) {
    addInOrder(insertMap.get(i.parent_xp_id)!);
  }
  visited.add(i.new_xp_id);
  orderedInserts.push(i);
}
for (const i of inserts) addInOrder(i);

for (const i of orderedInserts) {
  const parent = i.parent_xp_id ? `'${i.parent_xp_id}'` : 'NULL';
  applyParts.push(`INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('${i.new_xp_id}', '${sql(i.name_en)}', '${sql(i.name_fr)}', ${parent}, '${i.orgchart_id}', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;`);
}

// Step 2: Update kept rows — rename, set orgchart_id, set parent.
applyParts.push(`
-- ── Step 2: Update kept rows (rename + relink parent + set orgchart_id) ──`);
for (const k of keeps) {
  const parent = k.new_parent_xp_id ? `'${k.new_parent_xp_id}'` : 'NULL';
  applyParts.push(`UPDATE public.ministries SET
    name_en = '${sql(k.new_name_en)}',
    name_fr = '${sql(k.new_name_fr)}',
    parent_ministry_id = ${parent},
    orgchart_id = '${k.orgchart_id}',
    updated_at = now()
  WHERE id = '${k.xp_id}';`);
}

// Step 3: Repoint FKs from soft-delete rows to retargets (only where retarget exists).
applyParts.push(`
-- ── Step 3: Repoint FKs from soft-deleted rows to their retargets ──`);
for (const d of deletes) {
  if (!d.retarget_xp_id) continue;
  // goals.owner_ministry_id
  if (d.goals_count > 0) {
    applyParts.push(`UPDATE public.goals SET owner_ministry_id = '${d.retarget_xp_id}'
  WHERE owner_ministry_id = '${d.xp_id}';  -- ${d.goals_count} row(s): ${sql(d.xp_name_en)} → ${sql(d.retarget_label)}`);
  }
  // meetings.ministry_id
  if (d.meetings_count > 0) {
    applyParts.push(`UPDATE public.meetings SET ministry_id = '${d.retarget_xp_id}'
  WHERE ministry_id = '${d.xp_id}';  -- ${d.meetings_count} row(s)`);
  }
  // events.ministry_id
  if (d.events_count > 0) {
    applyParts.push(`UPDATE public.events SET ministry_id = '${d.retarget_xp_id}'
  WHERE ministry_id = '${d.xp_id}';  -- ${d.events_count} row(s)`);
  }
  // people_ministries.ministry_id (delete potential dup before update — UNIQUE on (person_id, ministry_id))
  if (d.members_count > 0) {
    applyParts.push(`-- people_ministries: drop rows that would collide on (person_id, ministry_id) after repoint, then update
DELETE FROM public.people_ministries pm1
  WHERE pm1.ministry_id = '${d.xp_id}'
    AND EXISTS (
      SELECT 1 FROM public.people_ministries pm2
      WHERE pm2.person_id = pm1.person_id
        AND pm2.ministry_id = '${d.retarget_xp_id}'
    );
UPDATE public.people_ministries SET ministry_id = '${d.retarget_xp_id}'
  WHERE ministry_id = '${d.xp_id}';  -- ${d.members_count} row(s)`);
  }
}

// Step 4: Soft-delete the obsolete rows.
applyParts.push(`
-- ── Step 4: Soft-delete obsolete ministry rows ──`);
for (const d of deletes) {
  applyParts.push(`UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '${d.xp_id}';  -- ${sql(d.xp_name_en)} (${sql(d.reason)})`);
}

applyParts.push(`
-- ── Done. ──
-- Verify with the queries in docs/orgchart-reseed-verify.md.
COMMIT;
`);

writeFileSync(applyFile, applyParts.join('\n'));
console.log('wrote', applyFile);

// ─────────────────────────────────────────────────────────────────────────
// Rollback SQL — reverses apply by restoring from snapshot tables.
// ─────────────────────────────────────────────────────────────────────────
const rollback = `-- Orgchart Reseed: ROLLBACK
-- Generated by scripts/orgchart-reseed-emit-sql.ts
-- Plan timestamp: ${new Date().toISOString()}
--
-- This file is NOT in supabase/migrations/. It is intentionally outside the
-- migrations directory so it does not auto-apply. Paste into Supabase SQL
-- Editor only when you want to undo a reseed apply.
--
-- Strategy:
--   1. Restore goals/meetings/events FKs by joining against the snapshot tables.
--   2. Truncate-and-restore ministries and people_ministries from snapshot.
--   3. Drop the snapshot tables and manifest entry.

BEGIN;

-- Safety check: snapshot must exist for ts ${ts}.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public._reseed_manifest WHERE id = '${ts}') THEN
    RAISE EXCEPTION 'No reseed snapshot ${ts} found. Nothing to roll back.';
  END IF;
END $$;

-- ── Step 1: Restore goals/meetings/events FKs from snapshot ──
UPDATE public.goals g
  SET owner_ministry_id = s.owner_ministry_id
  FROM public._reseed_snapshot_goals_owner s
  WHERE g.id = s.id
    AND g.owner_ministry_id IS DISTINCT FROM s.owner_ministry_id;

UPDATE public.meetings m
  SET ministry_id = s.ministry_id
  FROM public._reseed_snapshot_meetings_ministry s
  WHERE m.id = s.id
    AND m.ministry_id IS DISTINCT FROM s.ministry_id;

UPDATE public.events e
  SET ministry_id = s.ministry_id
  FROM public._reseed_snapshot_events_ministry s
  WHERE e.id = s.id
    AND e.ministry_id IS DISTINCT FROM s.ministry_id;

-- ── Step 2a: Restore ministries table ──
-- Delete rows that did not exist in the snapshot (the ones we INSERTed).
DELETE FROM public.ministries
  WHERE id NOT IN (SELECT id FROM public._reseed_snapshot_ministries);

-- Restore every column on the rows that existed before (this also un-soft-deletes).
UPDATE public.ministries m SET
  name_en = s.name_en,
  name_fr = s.name_fr,
  description_en = s.description_en,
  description_fr = s.description_fr,
  leader_id = s.leader_id,
  parent_ministry_id = s.parent_ministry_id,
  orgchart_id = s.orgchart_id,
  status = s.status,
  deleted_at = s.deleted_at,
  updated_at = s.updated_at
  FROM public._reseed_snapshot_ministries s
  WHERE m.id = s.id;

-- ── Step 2b: Restore people_ministries ──
TRUNCATE public.people_ministries;
INSERT INTO public.people_ministries SELECT * FROM public._reseed_snapshot_people_ministries;

-- ── Step 3: Drop snapshot tables and manifest entry ──
DROP TABLE public._reseed_snapshot_ministries;
DROP TABLE public._reseed_snapshot_people_ministries;
DROP TABLE public._reseed_snapshot_goals_owner;
DROP TABLE public._reseed_snapshot_meetings_ministry;
DROP TABLE public._reseed_snapshot_events_ministry;
DELETE FROM public._reseed_manifest WHERE id = '${ts}';

COMMIT;

-- Verify post-rollback:
--   SELECT count(*) FROM public.ministries WHERE deleted_at IS NULL;  -- should match pre-reseed count
--   SELECT count(*) FROM public.people_ministries;
`;

writeFileSync(rollbackFile, rollback);
console.log('wrote', rollbackFile);

// ─────────────────────────────────────────────────────────────────────────
// Verify markdown
// ─────────────────────────────────────────────────────────────────────────
const verify = `# Orgchart Reseed — Post-Apply Verification

After pasting both migrations (snapshot then apply) into Supabase SQL Editor, run these read-only queries to confirm the reseed worked. All should return the expected values without errors.

## 1. Snapshot exists

\`\`\`sql
SELECT * FROM public._reseed_manifest WHERE id = '${ts}';
\`\`\`

Expected: one row, with original counts (ministries before reseed, etc.).

## 2. New active ministry count

\`\`\`sql
SELECT count(*) FROM public.ministries WHERE deleted_at IS NULL;
\`\`\`

Expected: **${keeps.length + inserts.length}** rows (was ${keeps.length + deletes.length} before).

## 3. Soft-deleted count

\`\`\`sql
SELECT count(*) FROM public.ministries WHERE deleted_at IS NOT NULL;
\`\`\`

Expected: **${deletes.length}** rows.

## 4. Every active row has an orgchart_id

\`\`\`sql
SELECT id, name_en FROM public.ministries WHERE deleted_at IS NULL AND orgchart_id IS NULL;
\`\`\`

Expected: **0 rows**.

## 5. No orphaned FKs

\`\`\`sql
-- Goals pointing at soft-deleted ministries
SELECT g.id, g.title_en, m.name_en
  FROM public.goals g
  JOIN public.ministries m ON m.id = g.owner_ministry_id
  WHERE m.deleted_at IS NOT NULL;

-- Meetings pointing at soft-deleted ministries
SELECT mt.id, mt.title_en, m.name_en
  FROM public.meetings mt
  JOIN public.ministries m ON m.id = mt.ministry_id
  WHERE m.deleted_at IS NOT NULL;

-- Events pointing at soft-deleted ministries
SELECT e.id, e.title_en, m.name_en
  FROM public.events e
  JOIN public.ministries m ON m.id = e.ministry_id
  WHERE m.deleted_at IS NOT NULL;
\`\`\`

Expected: **0 rows** for all three.

## 6. Tree integrity

\`\`\`sql
-- Top-level ministries (should be the 9 from orgchart)
SELECT name_en, orgchart_id FROM public.ministries
  WHERE deleted_at IS NULL AND parent_ministry_id IS NULL
  ORDER BY name_en;
\`\`\`

Expected: 9 rows — Church-Wide Initiatives, Connections Ministry, Discipleship & Spiritual Formation, Next Gen Ministry, Operations & Administration, Outreach & Mission, Pastoral Care & Community Life, Prayer Ministry, Worship Experience.

\`\`\`sql
-- Every active row's parent must also be active
SELECT m.id, m.name_en, p.name_en AS parent
  FROM public.ministries m
  LEFT JOIN public.ministries p ON p.id = m.parent_ministry_id
  WHERE m.deleted_at IS NULL
    AND m.parent_ministry_id IS NOT NULL
    AND p.deleted_at IS NOT NULL;
\`\`\`

Expected: **0 rows**.

## 7. Phase 1 backfill should now show 0 unlinked ministries

Open Admin → Orgchart Sync. The "Backfill Ministries" panel should display "All ministries are linked." and the UnlinkedBanner on Ministries / PersonProfile pages should hide (assuming the people backfill is also done).

## If something looks wrong

Run \`scripts/orgchart-reseed-rollback.sql\` in Supabase SQL Editor to revert.
`;
writeFileSync(verifyFile, verify);
console.log('wrote', verifyFile);

console.log('\nDone.');
console.log(`  keep:        ${keeps.length}`);
console.log(`  insert:      ${inserts.length}`);
console.log(`  soft-delete: ${deletes.length}`);
