-- Orgchart Reseed: ROLLBACK
-- Generated by scripts/orgchart-reseed-emit-sql.ts
-- Plan timestamp: 2026-05-05T15:55:23.684Z
--
-- This file is NOT in supabase/migrations/. It is intentionally outside the
-- migrations directory so it does not auto-apply. Paste into Supabase SQL
-- Editor only when you want to undo a reseed apply.
--
-- Strategy:
--   1. Restore goals/meetings/events FKs by joining against the snapshot tables.
--   2. Truncate-and-restore ministries and people_ministries from snapshot.
--   3. Drop the snapshot tables and manifest entry.

BEGIN;

-- Safety check: snapshot must exist for ts 20260505155403.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public._reseed_manifest WHERE id = '20260505155403') THEN
    RAISE EXCEPTION 'No reseed snapshot 20260505155403 found. Nothing to roll back.';
  END IF;
END $$;

-- ── Step 1: Restore goals/meetings/events FKs from snapshot ──
UPDATE public.goals g
  SET owner_ministry_id = s.owner_ministry_id
  FROM public._reseed_snapshot_goals_owner s
  WHERE g.id = s.id
    AND g.owner_ministry_id IS DISTINCT FROM s.owner_ministry_id;

UPDATE public.meetings m
  SET ministry_id = s.ministry_id
  FROM public._reseed_snapshot_meetings_ministry s
  WHERE m.id = s.id
    AND m.ministry_id IS DISTINCT FROM s.ministry_id;

UPDATE public.events e
  SET ministry_id = s.ministry_id
  FROM public._reseed_snapshot_events_ministry s
  WHERE e.id = s.id
    AND e.ministry_id IS DISTINCT FROM s.ministry_id;

-- ── Step 2a: Restore ministries table ──
-- Delete rows that did not exist in the snapshot (the ones we INSERTed).
DELETE FROM public.ministries
  WHERE id NOT IN (SELECT id FROM public._reseed_snapshot_ministries);

-- Restore every column on the rows that existed before (this also un-soft-deletes).
UPDATE public.ministries m SET
  name_en = s.name_en,
  name_fr = s.name_fr,
  description_en = s.description_en,
  description_fr = s.description_fr,
  leader_id = s.leader_id,
  parent_ministry_id = s.parent_ministry_id,
  orgchart_id = s.orgchart_id,
  status = s.status,
  deleted_at = s.deleted_at,
  updated_at = s.updated_at
  FROM public._reseed_snapshot_ministries s
  WHERE m.id = s.id;

-- ── Step 2b: Restore people_ministries ──
TRUNCATE public.people_ministries;
INSERT INTO public.people_ministries SELECT * FROM public._reseed_snapshot_people_ministries;

-- ── Step 3: Drop snapshot tables and manifest entry ──
DROP TABLE public._reseed_snapshot_ministries;
DROP TABLE public._reseed_snapshot_people_ministries;
DROP TABLE public._reseed_snapshot_goals_owner;
DROP TABLE public._reseed_snapshot_meetings_ministry;
DROP TABLE public._reseed_snapshot_events_ministry;
DELETE FROM public._reseed_manifest WHERE id = '20260505155403';

COMMIT;

-- Verify post-rollback:
--   SELECT count(*) FROM public.ministries WHERE deleted_at IS NULL;  -- should match pre-reseed count
--   SELECT count(*) FROM public.people_ministries;
