-- Orgchart Reseed: APPLY (file 02 of 2)
-- Generated by scripts/orgchart-reseed-emit-sql.ts
-- Plan timestamp: 2026-05-05T15:55:23.684Z
--
-- DO NOT RUN before the snapshot migration (file 01). This file mutates
-- ministries, people_ministries, goals.owner_ministry_id, meetings.ministry_id,
-- and events.ministry_id. Wrapped in a transaction so partial failure is
-- impossible.

BEGIN;

-- Safety check: snapshot must exist.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public._reseed_manifest WHERE id = '20260505155403') THEN
    RAISE EXCEPTION 'Reseed snapshot 20260505155403 not found. Run the snapshot migration first.';
  END IF;
END $$;


-- ── Step 1: Insert new ministry rows for orgchart nodes missing locally ──
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('3177f4f1-ebf6-4356-acca-a0b64cb46d6e', 'Worship Experience', 'Worship Experience', NULL, 'we-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('8c83f0b1-b0f5-4379-931e-4e6c4743791c', 'Instrumentalist', 'Instrumentalist', '465fe65e-b567-4730-9d2b-e1348f79e786', 'vol-076', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('adf68604-91d8-4d53-ade6-21462ffacae6', 'Social Media', 'Social Media', '6dd3d295-53a5-4d75-9a0b-c3fa83976b3b', 'f35e748e-44bc-4c66-9912-079187593090', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('3f021985-56c2-4cbf-a1db-5e0240de9a87', 'Production Teams', 'Production Teams', '3177f4f1-ebf6-4356-acca-a0b64cb46d6e', 'pr-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('3459f0c6-0b5a-4a8d-b14b-5f72891ff4af', 'Production Director', 'Production Director', '3f021985-56c2-4cbf-a1db-5e0240de9a87', 'pr-dir-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('31a15a94-f928-44a6-ac88-856ad51507ac', 'Lighting', 'Lighting', '3f021985-56c2-4cbf-a1db-5e0240de9a87', 'pr-light-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('3e9f0a86-e749-44bc-b966-4d185bfb3ce2', 'Video / Livestream', 'Video / Livestream', '3f021985-56c2-4cbf-a1db-5e0240de9a87', 'pr-vid-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('d94833fa-a135-4c41-ab51-04adf8df211a', 'Presentation', 'Presentation', '3f021985-56c2-4cbf-a1db-5e0240de9a87', 'pr-pres-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('3d4ed790-a1ae-4b25-b675-61e86d7ca813', 'Stage / Service Flow', 'Stage / Service Flow', '3f021985-56c2-4cbf-a1db-5e0240de9a87', 'pr-stage-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('b743eb08-a7b9-470d-bbd0-6df40991e476', 'Post Production Team', 'Post Production Team', '3f021985-56c2-4cbf-a1db-5e0240de9a87', 'a836182c-a540-499e-ad20-c6704b091a45', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('ac3e998f-2122-483b-ae1f-3399b832de63', 'Greeter Team Lead', 'Greeter Team Lead', 'e49d7590-3565-4e6f-bb8d-2d786342e19e', 'vol-034', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('43e76804-8dcd-4f62-becf-17b040c9bf2a', 'Usher Team Leader', 'Usher Team Leader', '1cb97af6-d36c-4ed9-bc8d-d90615044633', 'vol-061', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('b2fa5a4f-f2fe-40aa-8c35-d3a8618d6062', 'Ushers Leader', 'Ushers Leader', '1cb97af6-d36c-4ed9-bc8d-d90615044633', 'vol-065', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('920c1fc6-ce83-4f29-9d00-10129de2833b', 'Language Support', 'Language Support', '3177f4f1-ebf6-4356-acca-a0b64cb46d6e', 'interp-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('4bf43335-6d09-4c37-a41a-e3e7ec82153e', 'Service Coordination', 'Service Coordination', '3177f4f1-ebf6-4356-acca-a0b64cb46d6e', 'we-sc-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('ca924cba-d5d5-4bd2-a180-202f8e69d4ee', 'Intercession French', 'Intercession French', '6d6b7797-e53d-4130-9510-b1497af618d4', 'f14fea0d-1530-4395-8a9d-b12599b85673', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('632bd8fb-c7fc-41d2-ac06-bff70f2fefe6', 'Pray First', 'Pray First', '6d6b7797-e53d-4130-9510-b1497af618d4', 'b7aa3e74-efeb-41d7-8bf2-2ba410c88d8e', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('7b87bebf-0ab3-411e-b747-859c417453fa', 'Midi en Prière', 'Midi en Prière', '6d6b7797-e53d-4130-9510-b1497af618d4', '80c7d6f4-74dd-47fa-85e1-f9761a45ba47', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('5fa69967-6cc0-4321-8cd6-718a69379d76', 'Thrive Now Thursdays (TNT)', 'Thrive Now Thursdays (TNT)', '6d6b7797-e53d-4130-9510-b1497af618d4', '28e04a45-39a2-4b08-a6f3-94140b7f9bb4', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('378aecfa-537f-4a0b-aeeb-4697ec6f6ae7', 'Friday Night Prayer', 'Friday Night Prayer', '6d6b7797-e53d-4130-9510-b1497af618d4', 'ab21fb15-dee1-40a8-b487-275d80aa59fc', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('9b6e7d24-602f-4c07-8d58-d5ed51cbb6d7', 'Intercession English', 'Intercession English', '6d6b7797-e53d-4130-9510-b1497af618d4', '9ce9d23b-bc7a-4919-a060-e67b7de16734', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('f9c7f264-9895-4d6f-bc11-93b93b0f5724', 'End-of-month night prayer', 'End-of-month night prayer', '6d6b7797-e53d-4130-9510-b1497af618d4', '1324ae0b-b6ac-49b3-834f-6d375402029e', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('cfbed831-eef8-4fbc-a8f5-b4cf7084a8d0', 'Delivrance Ministry', 'Delivrance Ministry', '6d6b7797-e53d-4130-9510-b1497af618d4', '90d2fcae-2d52-427b-9aba-23262db8d671', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('66220f06-ceac-4e73-b699-a91bd9080b20', 'Connections Ministry', 'Connections Ministry', NULL, 'as-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('49d7ea68-0dd8-4b26-9b30-00aaa194eb8c', 'Guest Follow-up Lead', 'Guest Follow-up Lead', '66220f06-ceac-4e73-b699-a91bd9080b20', 'vol-032', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('6add5c22-410c-46bc-8b7c-a5dec0e57d62', 'Prochaines étapes', 'Prochaines étapes', '66220f06-ceac-4e73-b699-a91bd9080b20', 'f1a7f3bb-0c90-4250-b7e5-69c19a95b914', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('5af5cbf3-b841-4b36-bc22-a89427db96d7', 'Growth Track', 'Growth Track', '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0', '34ec4a36-6e28-4e92-b4e4-e2295caa29b4', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('6a87cf37-cf7c-4577-97da-b13b1c0ae9b4', 'Leadership Development', 'Leadership Development', '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0', 'ld-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('1d5b88d2-daa0-4e7d-a424-f9a1a03f0987', 'MC Academy', 'MC Academy', '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0', '7381a717-0df8-41db-85fd-c927a0e1f5c9', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('53c49444-72b6-445e-8735-8bfc0df443ac', 'Sacrements & Weddings', 'Sacrements & Weddings', '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0', 'sac-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('d7384c19-ce6e-4fe6-ad74-7f2b7000f957', 'Next Gen Ministry', 'Next Gen Ministry', NULL, 'ng-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('5f4ed1e1-c520-423a-9aa1-aee2b1abda59', 'Kids Ministry Leader', 'Kids Ministry Leader', '60475845-1f2e-447f-8ac5-4dc06a2aca39', 'vol-137', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('78e8b810-54b4-43bf-b968-01dae88d27c4', 'YAM English', 'YAM English', 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957', 'ya-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('465afee0-7825-45fd-bdd0-9ecb20db9715', 'YAM French', 'YAM French', 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957', '5cca8ebc-32bb-4882-8157-7c153cf7c89e', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('54295607-eb47-4720-b6c6-0adb21c7153c', 'Pastoral Care & Community Life', 'Pastoral Care & Community Life', NULL, 'pc-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('f4feb208-6794-47c3-a16f-c1917c6fb7ee', 'Counseling', 'Counseling', '54295607-eb47-4720-b6c6-0adb21c7153c', 'cn-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('9ba03001-5c41-4265-9e82-861e22767927', 'Hospital Care', 'Hospital Care', '54295607-eb47-4720-b6c6-0adb21c7153c', 'hc-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('e81f6ba3-8188-4d2c-b582-135abfdf74f0', 'Women''s Ministry', 'Women''s Ministry', '54295607-eb47-4720-b6c6-0adb21c7153c', '5f910cf8-e22d-4497-af61-8c55afe935dc', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('cdd92da3-bf47-4b83-a6f2-74d6d44e7491', 'Community Outreach', 'Community Outreach', 'dfb94591-b50e-4bc6-b810-a35b1cfa7573', 'co-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('3c72d340-6174-45a2-9157-0993dc357cc5', 'Operations & Administration', 'Operations & Administration', NULL, 'oa-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('453d4b05-0d3b-453d-a7c7-ecebff563f9c', 'Office Admin', 'Office Admin', '3c72d340-6174-45a2-9157-0993dc357cc5', 'oadm-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('2dcc918d-1310-41a5-8045-7098079373d4', 'Finance', 'Finance', '3c72d340-6174-45a2-9157-0993dc357cc5', 'fin-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('1c058853-34a3-44df-8e65-69e4d4653940', 'Facilities', 'Facilities', '3c72d340-6174-45a2-9157-0993dc357cc5', 'fac-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('c9f62430-3be2-456e-aabf-d1cf8be20b64', 'Church-Wide Initiatives', 'Church-Wide Initiatives', NULL, 'cw-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('8d307a84-59eb-418e-97c0-1cca0de6a8ac', '1SPJ Programs', '1SPJ Programs', 'c9f62430-3be2-456e-aabf-d1cf8be20b64', 'ow-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('929796c5-a85f-499b-8533-4ddd67f4d1ec', '21 Days Program', '21 Days Program', 'c9f62430-3be2-456e-aabf-d1cf8be20b64', 'tod-001', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;
INSERT INTO public.ministries (id, name_en, name_fr, parent_ministry_id, orgchart_id, status, created_at, updated_at)
  VALUES ('1142ed52-c087-4af5-a136-8006695a6463', 'Easter Celebration', 'Easter Celebration', 'c9f62430-3be2-456e-aabf-d1cf8be20b64', 'bcb17673-bf91-4a5d-8124-b489beaeea19', 'active', now(), now())
  ON CONFLICT (id) DO NOTHING;

-- ── Step 2: Update kept rows (rename + relink parent + set orgchart_id) ──
UPDATE public.ministries SET
    name_en = 'Communication Team',
    name_fr = 'Communication Team',
    parent_ministry_id = '3177f4f1-ebf6-4356-acca-a0b64cb46d6e',
    orgchart_id = 'mm-001',
    updated_at = now()
  WHERE id = '6dd3d295-53a5-4d75-9a0b-c3fa83976b3b';
UPDATE public.ministries SET
    name_en = 'Creative Team',
    name_fr = 'Creative Team',
    parent_ministry_id = '6dd3d295-53a5-4d75-9a0b-c3fa83976b3b',
    orgchart_id = '5842f537-ca08-4d88-897c-ef1b2aa84260',
    updated_at = now()
  WHERE id = '05837555-0c84-4db4-b42b-27391d93c445';
UPDATE public.ministries SET
    name_en = 'Discipleship & Spiritual Formation',
    name_fr = 'Discipleship & Spiritual Formation',
    parent_ministry_id = NULL,
    orgchart_id = 'ds-001',
    updated_at = now()
  WHERE id = '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0';
UPDATE public.ministries SET
    name_en = 'Evangelism',
    name_fr = 'Evangelism',
    parent_ministry_id = 'dfb94591-b50e-4bc6-b810-a35b1cfa7573',
    orgchart_id = 'ev-001',
    updated_at = now()
  WHERE id = 'cea77727-376d-4ba0-b83b-07f127b67870';
UPDATE public.ministries SET
    name_en = 'Family Care',
    name_fr = 'Family Care',
    parent_ministry_id = '54295607-eb47-4720-b6c6-0adb21c7153c',
    orgchart_id = 'fc-001',
    updated_at = now()
  WHERE id = 'f417a33f-caee-4d07-b2d1-948d4cd08e50';
UPDATE public.ministries SET
    name_en = 'Greeters',
    name_fr = 'Greeters',
    parent_ministry_id = '11111111-1111-1111-1111-111111111106',
    orgchart_id = 'hs-greet-001',
    updated_at = now()
  WHERE id = 'e49d7590-3565-4e6f-bb8d-2d786342e19e';
UPDATE public.ministries SET
    name_en = 'Hospitality',
    name_fr = 'Hospitality',
    parent_ministry_id = '3177f4f1-ebf6-4356-acca-a0b64cb46d6e',
    orgchart_id = 'hs-001',
    updated_at = now()
  WHERE id = '11111111-1111-1111-1111-111111111106';
UPDATE public.ministries SET
    name_en = 'Kids Ministry',
    name_fr = 'Kids Ministry',
    parent_ministry_id = 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957',
    orgchart_id = 'km-001',
    updated_at = now()
  WHERE id = '60475845-1f2e-447f-8ac5-4dc06a2aca39';
UPDATE public.ministries SET
    name_en = 'MC Music',
    name_fr = 'MC Music',
    parent_ministry_id = '3177f4f1-ebf6-4356-acca-a0b64cb46d6e',
    orgchart_id = 'wt-001',
    updated_at = now()
  WHERE id = '3be68ee3-807f-4412-8f2a-da4d2f073655';
UPDATE public.ministries SET
    name_en = 'MC Music English',
    name_fr = 'MC Music English',
    parent_ministry_id = '3be68ee3-807f-4412-8f2a-da4d2f073655',
    orgchart_id = 'wt-eng-001',
    updated_at = now()
  WHERE id = '465fe65e-b567-4730-9d2b-e1348f79e786';
UPDATE public.ministries SET
    name_en = 'MC Music French',
    name_fr = 'MC Music French',
    parent_ministry_id = '3be68ee3-807f-4412-8f2a-da4d2f073655',
    orgchart_id = 'wt-fr-001',
    updated_at = now()
  WHERE id = '38e7b636-78b4-484b-aeca-f2b71560e60f';
UPDATE public.ministries SET
    name_en = 'Membership Management',
    name_fr = 'Membership Management',
    parent_ministry_id = '66220f06-ceac-4e73-b699-a91bd9080b20',
    orgchart_id = 'mi-001',
    updated_at = now()
  WHERE id = 'e0051635-49b4-4e9c-a2de-4d4f28212edc';
UPDATE public.ministries SET
    name_en = 'Men''s Ministry',
    name_fr = 'Men''s Ministry',
    parent_ministry_id = '54295607-eb47-4720-b6c6-0adb21c7153c',
    orgchart_id = 'd0929316-0716-432f-b7e0-cbb0a05f87c0',
    updated_at = now()
  WHERE id = '424ef162-f729-4960-b5fe-28969cffc108';
UPDATE public.ministries SET
    name_en = 'Missions',
    name_fr = 'Missions',
    parent_ministry_id = 'dfb94591-b50e-4bc6-b810-a35b1cfa7573',
    orgchart_id = 'gm-001',
    updated_at = now()
  WHERE id = 'f9b1be6a-6db9-4727-ba77-e6f7ddaa8ac6';
UPDATE public.ministries SET
    name_en = 'Next Steps English',
    name_fr = 'Next Steps English',
    parent_ministry_id = '66220f06-ceac-4e73-b699-a91bd9080b20',
    orgchart_id = 'ns-001',
    updated_at = now()
  WHERE id = 'efafcfae-8bec-48d3-8238-d7b548ba7b15';
UPDATE public.ministries SET
    name_en = 'Outreach & Mission',
    name_fr = 'Outreach & Mission',
    parent_ministry_id = NULL,
    orgchart_id = 'om-001',
    updated_at = now()
  WHERE id = 'dfb94591-b50e-4bc6-b810-a35b1cfa7573';
UPDATE public.ministries SET
    name_en = 'Parking',
    name_fr = 'Parking',
    parent_ministry_id = '11111111-1111-1111-1111-111111111106',
    orgchart_id = 'hs-park-001',
    updated_at = now()
  WHERE id = '32402d01-da22-48e4-9ab2-fc108ba3f749';
UPDATE public.ministries SET
    name_en = 'Guest Services',
    name_fr = 'Guest Services',
    parent_ministry_id = '11111111-1111-1111-1111-111111111106',
    orgchart_id = 'hs-gs-001',
    updated_at = now()
  WHERE id = 'a109b62d-a4ad-4478-97b9-b5133c64103b';
UPDATE public.ministries SET
    name_en = 'Prayer Ministry',
    name_fr = 'Prayer Ministry',
    parent_ministry_id = NULL,
    orgchart_id = 'pt-001',
    updated_at = now()
  WHERE id = '6d6b7797-e53d-4130-9510-b1497af618d4';
UPDATE public.ministries SET
    name_en = 'Security',
    name_fr = 'Security',
    parent_ministry_id = '11111111-1111-1111-1111-111111111106',
    orgchart_id = 'hs-sec-001',
    updated_at = now()
  WHERE id = '8a2661e2-6b94-4b74-9a24-c250107280ec';
UPDATE public.ministries SET
    name_en = 'Small Groups',
    name_fr = 'Small Groups',
    parent_ministry_id = '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0',
    orgchart_id = 'sg-001',
    updated_at = now()
  WHERE id = '11111111-1111-1111-1111-111111111105';
UPDATE public.ministries SET
    name_en = 'Sound',
    name_fr = 'Sound',
    parent_ministry_id = '3f021985-56c2-4cbf-a1db-5e0240de9a87',
    orgchart_id = 'pr-aud-001',
    updated_at = now()
  WHERE id = 'f50612a7-73f8-4a10-a450-5e0c958f7b7b';
UPDATE public.ministries SET
    name_en = 'Technology',
    name_fr = 'Technology',
    parent_ministry_id = '3c72d340-6174-45a2-9157-0993dc357cc5',
    orgchart_id = 'tech-001',
    updated_at = now()
  WHERE id = '5179488b-db29-491a-967d-8d330317a6b4';
UPDATE public.ministries SET
    name_en = 'Ushers',
    name_fr = 'Ushers',
    parent_ministry_id = '11111111-1111-1111-1111-111111111106',
    orgchart_id = 'hs-ush-001',
    updated_at = now()
  WHERE id = '1cb97af6-d36c-4ed9-bc8d-d90615044633';
UPDATE public.ministries SET
    name_en = 'Youth Ministry',
    name_fr = 'Youth Ministry',
    parent_ministry_id = 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957',
    orgchart_id = 'sm-001',
    updated_at = now()
  WHERE id = '11111111-1111-1111-1111-111111111102';

-- ── Step 3: Repoint FKs from soft-deleted rows to their retargets ──
UPDATE public.goals SET owner_ministry_id = '684a1fd6-7cbd-4ce6-8600-2a50d8581ea0'
  WHERE owner_ministry_id = 'e44e3134-1b88-4b4c-af88-876adadea200';  -- 2 row(s): Discipleship → Discipleship Ministry (via override → Discipleship Ministry)
UPDATE public.goals SET owner_ministry_id = '11111111-1111-1111-1111-111111111106'
  WHERE owner_ministry_id = '4d44210d-7d59-43a5-aca2-5256e5d04e02';  -- 12 row(s): Greeting / Entry Team → Hospitality Services (via ancestor)
UPDATE public.events SET ministry_id = '60475845-1f2e-447f-8ac5-4dc06a2aca39'
  WHERE ministry_id = '0b8ec928-b1a6-4f8d-b456-04704b736fd9';  -- 34 row(s)
UPDATE public.goals SET owner_ministry_id = 'f417a33f-caee-4d07-b2d1-948d4cd08e50'
  WHERE owner_ministry_id = '13dfbe9e-5ab5-4008-a16c-2b7cdce2bbc7';  -- 9 row(s): Ladies Ministry → Family Care Ministry (via ancestor)
UPDATE public.goals SET owner_ministry_id = 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957'
  WHERE owner_ministry_id = 'd1f16655-cc60-43e4-8dc5-5de872aaa7c8';  -- 14 row(s): Next-Gen Ministry → Next Gen Ministry (via override → Next Gen Ministry)
UPDATE public.events SET ministry_id = 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957'
  WHERE ministry_id = '69657b57-e65c-49a0-bde4-55e5d73712e2';  -- 1 row(s)
UPDATE public.goals SET owner_ministry_id = 'dfb94591-b50e-4bc6-b810-a35b1cfa7573'
  WHERE owner_ministry_id = '11111111-1111-1111-1111-111111111104';  -- 1 row(s): Outreach & Missions → Outreach Ministry (via override → Outreach Ministry)
UPDATE public.events SET ministry_id = 'dfb94591-b50e-4bc6-b810-a35b1cfa7573'
  WHERE ministry_id = '11111111-1111-1111-1111-111111111104';  -- 13 row(s)
UPDATE public.goals SET owner_ministry_id = '6d6b7797-e53d-4130-9510-b1497af618d4'
  WHERE owner_ministry_id = '2d308bd8-bdc8-4a76-9d1e-c413a0ed36d4';  -- 8 row(s): Prayer Teams → Prayer Ministry (via override → Prayer Ministry)
UPDATE public.goals SET owner_ministry_id = '53c49444-72b6-445e-8735-8bfc0df443ac'
  WHERE owner_ministry_id = 'd8e36ab9-0ca6-4743-93af-35accb21e99e';  -- 8 row(s): Sacraments & Special Services → Sacrements & Weddings (via override → Sacrements & Weddings)
UPDATE public.goals SET owner_ministry_id = 'f417a33f-caee-4d07-b2d1-948d4cd08e50'
  WHERE owner_ministry_id = 'd8df6c44-263a-4119-9a89-45adf3a47a4c';  -- 8 row(s): Social Integration → Family Care Ministry (via ancestor)
UPDATE public.goals SET owner_ministry_id = 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957'
  WHERE owner_ministry_id = '79c14313-7970-424e-bea7-d60e5d9a7ac4';  -- 9 row(s): Students Ministry → Next Gen Ministry (via override → Next Gen Ministry)
UPDATE public.goals SET owner_ministry_id = '11111111-1111-1111-1111-111111111106'
  WHERE owner_ministry_id = '820bd9f0-ded2-4b51-ad99-b53ff25479b1';  -- 12 row(s): Welcome Center Team → Hospitality Services (via ancestor)
UPDATE public.goals SET owner_ministry_id = 'd7384c19-ce6e-4fe6-ad74-7f2b7000f957'
  WHERE owner_ministry_id = '76b75fda-665d-4c90-91f1-b516dce7e3d1';  -- 8 row(s): Young Adults Ministry → Next Gen Ministry (via override → Next Gen Ministry)

-- ── Step 4: Soft-delete obsolete ministry rows ──
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = 'e44e3134-1b88-4b4c-af88-876adadea200';  -- Discipleship (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '4d44210d-7d59-43a5-aca2-5256e5d04e02';  -- Greeting / Entry Team (no orgchart counterpart)
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '557d577e-5a7e-4c9c-b2aa-1d9547990970';  -- Guest & Concierge Services (duplicate of Pastoral & Guest Services (a109b62d-a4ad-4478-97b9-b5133c64103b))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '0b8ec928-b1a6-4f8d-b456-04704b736fd9';  -- Kingdom Kidz (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '13dfbe9e-5ab5-4008-a16c-2b7cdce2bbc7';  -- Ladies Ministry (no orgchart counterpart)
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = 'd1f16655-cc60-43e4-8dc5-5de872aaa7c8';  -- Next-Gen Ministry (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '69657b57-e65c-49a0-bde4-55e5d73712e2';  -- NextGen Ministry (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '11111111-1111-1111-1111-111111111104';  -- Outreach & Missions (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '2d308bd8-bdc8-4a76-9d1e-c413a0ed36d4';  -- Prayer Teams (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = 'd8e36ab9-0ca6-4743-93af-35accb21e99e';  -- Sacraments & Special Services (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = 'd8df6c44-263a-4119-9a89-45adf3a47a4c';  -- Social Integration (no orgchart counterpart)
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '27a35d51-54f8-46df-a51c-35dbd9b7123b';  -- Students (no orgchart counterpart)
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '79c14313-7970-424e-bea7-d60e5d9a7ac4';  -- Students Ministry (manual override (delete))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = 'ab969079-a1e8-4d8e-b494-fca845177a12';  -- Ushers Team (duplicate of Ushers / Seating Team (1cb97af6-d36c-4ed9-bc8d-d90615044633))
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '820bd9f0-ded2-4b51-ad99-b53ff25479b1';  -- Welcome Center Team (no orgchart counterpart)
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '820e31b3-9a10-49ca-862e-eae39532fada';  -- Young Adults (no orgchart counterpart)
UPDATE public.ministries SET deleted_at = now(), updated_at = now()
  WHERE id = '76b75fda-665d-4c90-91f1-b516dce7e3d1';  -- Young Adults Ministry (manual override (delete))

-- ── Done. ──
-- Verify with the queries in docs/orgchart-reseed-verify.md.
COMMIT;
