-- Orgchart Reseed: SNAPSHOT (file 01 of 2)
-- Generated by scripts/orgchart-reseed-emit-sql.ts
-- Plan timestamp: 2026-05-05T15:55:23.682Z
--
-- This migration ONLY copies current state into _reseed_snapshot_* tables.
-- It is non-destructive: no rows in production tables are modified.
-- Apply this BEFORE the reseed apply migration.
-- The rollback script (scripts/orgchart-reseed-rollback.sql) reads from these
-- snapshot tables to restore the prior state if needed.

BEGIN;

-- Manifest table records the snapshot ts and original row counts so rollback
-- can verify there is something to restore.
CREATE TABLE IF NOT EXISTS public._reseed_manifest (
  id text PRIMARY KEY,
  taken_at timestamptz NOT NULL DEFAULT now(),
  ministries_count int NOT NULL,
  people_ministries_count int NOT NULL,
  goals_with_ministry_count int NOT NULL,
  meetings_with_ministry_count int NOT NULL,
  events_with_ministry_count int NOT NULL
);

-- Drop+recreate snapshot tables so this file is idempotent (safe to run twice).
DROP TABLE IF EXISTS public._reseed_snapshot_ministries;
DROP TABLE IF EXISTS public._reseed_snapshot_people_ministries;
DROP TABLE IF EXISTS public._reseed_snapshot_goals_owner;
DROP TABLE IF EXISTS public._reseed_snapshot_meetings_ministry;
DROP TABLE IF EXISTS public._reseed_snapshot_events_ministry;

CREATE TABLE public._reseed_snapshot_ministries AS
  SELECT * FROM public.ministries;

CREATE TABLE public._reseed_snapshot_people_ministries AS
  SELECT * FROM public.people_ministries;

-- Only the FK + identifier columns are needed for the rollback FK repoint.
CREATE TABLE public._reseed_snapshot_goals_owner AS
  SELECT id, owner_ministry_id FROM public.goals WHERE owner_ministry_id IS NOT NULL;

CREATE TABLE public._reseed_snapshot_meetings_ministry AS
  SELECT id, ministry_id FROM public.meetings WHERE ministry_id IS NOT NULL;

CREATE TABLE public._reseed_snapshot_events_ministry AS
  SELECT id, ministry_id FROM public.events WHERE ministry_id IS NOT NULL;

INSERT INTO public._reseed_manifest (
  id, ministries_count, people_ministries_count,
  goals_with_ministry_count, meetings_with_ministry_count, events_with_ministry_count
)
VALUES (
  '20260505155403',
  (SELECT count(*) FROM public._reseed_snapshot_ministries),
  (SELECT count(*) FROM public._reseed_snapshot_people_ministries),
  (SELECT count(*) FROM public._reseed_snapshot_goals_owner),
  (SELECT count(*) FROM public._reseed_snapshot_meetings_ministry),
  (SELECT count(*) FROM public._reseed_snapshot_events_ministry)
)
ON CONFLICT (id) DO UPDATE SET
  taken_at = now(),
  ministries_count = EXCLUDED.ministries_count,
  people_ministries_count = EXCLUDED.people_ministries_count,
  goals_with_ministry_count = EXCLUDED.goals_with_ministry_count,
  meetings_with_ministry_count = EXCLUDED.meetings_with_ministry_count,
  events_with_ministry_count = EXCLUDED.events_with_ministry_count;

COMMIT;

-- After running, verify with:
--   SELECT * FROM public._reseed_manifest;
--   SELECT count(*) FROM public._reseed_snapshot_ministries;        -- should equal ministries before reseed
--   SELECT count(*) FROM public._reseed_snapshot_people_ministries;
